Issue 3 edit an entry
jacobyi11/code-journal pull request #7
Opened 2022-02-18 03:36 UTC by jacobyi11

https://user-images.githubusercontent.com/96788421/154612804-e7f85035-5e6b-4fd1-ba57-134534895d04.mov

2022-02-18 16:38 UTC, thebearingedge requested changes

2022-02-18 16:38 UTC, thebearingedge commented on js/main.js
> +        listItem[i].replaceWith(renderJournal(updateObj));
Be sure to also replace the old entry in the data model with the updated one.

2022-02-18 16:38 UTC, thebearingedge commented on js/main.js
> +localStorage.clear();
You should be able to remove this line 4.

2022-02-19 04:18 UTC, jacobyi11 commented
https://user-images.githubusercontent.com/96788421/154785799-1cd361cc-c7f8-4dc8-8ca3-bb150bf61986.mov

2022-02-20 01:39 UTC, merged